Feature/43/modularization
gonzadiascenzi/YelpApp pull request #51
Opened 2022-04-25 18:13 UTC by simonipd

¿Cuáles son los tickets relevantes?

https://github.com/gonzadiascenzi/YelpApp/issues/43

¿Qué hace este Pull Request?

https://members.architectcoders.com/topic/4-8-modularizacion/

¿Por dónde debería empezar el revisor?

AppModule

2022-04-25 18:17 UTC, gonzadiascenzi approved these changes
Nice good job!

2022-04-26 01:06 UTC, JulianYbarra requested changes

2022-04-26 01:06 UTC, JulianYbarra commented on app/src/main/java/com/example/yelpapp/ui/main/BusinessAdapter.kt
> +            business.rating.let {
esta linea con el let { } esta de mas

2022-04-26 01:06 UTC, JulianYbarra commented on app/src/main/java/com/example/yelpapp/ui/detail/DetailViewModel.kt
> +    //private val business: Business
deberia recibir el id, y obtener de la db

2022-04-26 01:06 UTC, JulianYbarra commented on app/src/main/java/com/example/yelpapp/ui/main/MainViewModel.kt
> +    //private val businessRepository: BusinessRepository,
este comentario esta de mas

2022-04-26 01:06 UTC, JulianYbarra commented on app/src/main/java/com/example/yelpapp/ui/main/MainViewModel.kt
> +          /*  businessRepository.business
este comentario esta de mas

2022-04-26 01:06 UTC, JulianYbarra commented on app/src/main/java/com/example/yelpapp/ui/main/MainViewModel.kt
> +            //businessRepository.requestBusiness()
este comentario esta de mas

2022-04-26 01:06 UTC, JulianYbarra commented on data/src/main/java/com/example/yelpapp/data/datasource/BusinessRemoteDataSource.kt
> +            //List<Business> = service.searchBusinesses(lat,lng).businesses.map { it.toDomainModel() }
este comentario esta de mas

2022-04-26 01:06 UTC, JulianYbarra commented on domain/src/main/java/com/example/yelpapp/domain/Business.kt
>  @Parcelize
este no es necesario que sea Parcelize ahora que se busca por id en db

2022-04-26 01:06 UTC, JulianYbarra commented on domain/src/main/java/com/example/yelpapp/domain/Business.kt
> +) : Serializable
esto no es necesario, ya que se busca por id desde la db

2022-04-26 01:07 UTC, JulianYbarra commented
Tambien tene en cuenta que en algunas clases te quedo mal el nombre del package al que partenece.

2022-04-27 02:20 UTC, simonipd commented on data/src/main/java/com/example/yelpapp/data/datasource/BusinessRemoteDataSource.kt
> +            //List<Business> = service.searchBusinesses(lat,lng).businesses.map { it.toDomainModel() }
Codigo Eliminado

2022-04-27 02:20 UTC, simonipd commented on app/src/main/java/com/example/yelpapp/ui/main/MainViewModel.kt
> +            //businessRepository.requestBusiness()
Codigo Eliminado

2022-04-27 02:20 UTC, simonipd commented on app/src/main/java/com/example/yelpapp/ui/main/MainViewModel.kt
> +          /*  businessRepository.business
Codigo Eliminado

2022-04-27 02:20 UTC, simonipd commented on app/src/main/java/com/example/yelpapp/ui/main/MainViewModel.kt
> +    //private val businessRepository: BusinessRepository,
Codigo Eliminado

2022-04-27 02:20 UTC, simonipd commented on app/src/main/java/com/example/yelpapp/ui/main/BusinessAdapter.kt
> +            business.rating.let {
Codigo corregido

2022-04-28 01:55 UTC, JulianYbarra approved these changes

2022-04-28 15:13 UTC, borissoto approved these changes
Let's get this merged, dude.

2022-04-29 18:33 UTC, merged